name: Docker Image CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: set tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: docker hub login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build and push paperspigot
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ghcr.io/cownetwork/velocity:${{ steps.tag.outputs.tag }}
